### ISSUE TITLE
Privacy Manifest missing

### ISSUE THREAD

**Issue by mobru** [mapp-digital/MappIntelligence-iOS-v5#11]
Hey there,

with version [5.0.6.3](https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.6.3) you introduced a [Privacy Manifest](https://github.com/mapp-digital/MappIntelligence-iOS-v5/blob/master/MappIntelligencePrivacyInfo.xcprivacy). Unfortunately, this file is not available when adding the SDK via e.g. CocoaPods. This seems to be the case because MappIntelligence is served as a static lib, which does not include resources such as the Privacy Manifest. This could be solved (I think) by serving the SDK as a static framework, or as a dynamic lib.

Please fix this - who knows how Apple will handle a tracking SDK missing a Privacy Manifest once they are required.

---

As a side question: how come you only declare usage of the UserDefaults in your Privacy Manifest? Is this because all the actual tracking is being done by the apps utilizing the MappIntelligence SDK?

**Comment by stellatores** [comment]
@mobru thanks, we found the issue and will release it in our next release. 

Regarding the other question, we checked the list of required reason APIs and this is the only one we use: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by mobru** [comment]
@stellatores great, thanks!

And regarding my question: I did not only mean the `NSPrivacyAccessedAPITypes`, but also the `NSPrivacyCollectedDataTypes` (see [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)). I was thinking that maybe you collect the Device ID / `NSPrivacyCollectedDataTypeDeviceID`?

**Comment by stellatores** [comment]
@mobru our SDK only collects the data that is configured by the customer. We do not make use of the device ID and only assign a random user ID if the SDK is not in "anonymous mode": https://documentation.mapp.com/latest/en/anonymous-tracking-19104163.html

**Comment by stellatores** [comment]
@mobru we released the fix today that prevented the use of our privacy manifest file when using CocoaPods: https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.9
I close the issue now please let us know if you are still facing issues.
