### ISSUE TITLE
No more tracking after app was in background (v5.0.9)

### ISSUE THREAD

**Issue by ReneLindhorst** [mapp-digital/MappIntelligence-iOS-v5#12]
Version 5.0.9 was an important update as it added the privacy manifest, but we noticed a severe regression:
Once the app was in background, no more tracking events are fired when it becomes active again.

Looking at the 5.0.9 code, the problem is that `willEnterForeground` is never executed as the NSNotificationCenter code is commented out.

![2024-05-23 Screenshot Arc 15 08 46@2x](https://github.com/mapp-digital/MappIntelligence-iOS-v5/assets/135444/5a1cf114-3bfa-424b-8750-82505161c1bb)

**Comment by stellatores** [comment]
Thank you for reporting this. We are actively working on a fix and will be able to release it next week. We are also currently improving our regression tests before each release.

**Comment by stellatores** [comment]
Hi @ReneLindhorst we published the fix as a release candidate: https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.10-rc1
Please note that we are currently working on a new patch version on high prio where we also include additional tests and some more improvements to provide more stable versions in the future. Nevertheless I wanted to provide the specific fix as soon as possible so you can use the privacy manifest as well.

**Comment by ReneLindhorst** [comment]
@stellatores Thank you for providing the new version but sadly, it crashes on launch 🤯


![Screenshot Xcode](https://github.com/mapp-digital/MappIntelligence-iOS-v5/assets/135444/6ee4deb1-569f-435e-b73e-ad44ce77b525)

**Comment by stellatores** [comment]
@ReneLindhorst thanks for the reply. We tried installing the SDK via CocoaPods and SPM on both emulator and real devices and it launched correctly. Can you please include a few more details and steps to reproduce?

**Comment by ReneLindhorst** [comment]
@stellatores I had a brief look. As far as I understand, the following is happening:

- The App collects some tracking data and the SDK tries to send it to the server in `MIDatabaseManager fetchAllParametersForRequestID:andCompletitionHandler:`.
- In `MITrackerRequest sendRequestWith:andBody:andCompletition:` the requests returns an error (due to some router configuration of mine).
- This results in an invalidation of the URLSession.
- As the URLSessions isn't re-created anymore (`createUrlSession` got commented out), the next time the automatic retry mechanism tries to send the tracking data, it crashes.
  * > 'NSGenericException', reason: 'Task created in a session that has been invalidated'

https://github.com/mapp-digital/MappIntelligence-iOS-v5/blob/efba4bf603adf0dc3c426f2b40e16ae5cfa315b5/MappIntelligence/Network/Tracking%20Request/MITrackerRequest.m#L79-L95

**Comment by stellatores** [comment]
Thank you @ReneLindhorst we fixed this issue on our master branch and will release it in another release candidate version by Monday next week latest.

**Comment by danielr** [comment]
@stellatores Any news on the new RC?

**Comment by stellatores** [comment]
@danielr Sorry for the delay, we needed to include one more fix for a customer (https://github.com/mapp-digital/MappIntelligence-iOS-v5/commit/994b2bab14398980b00e2f9d6c8ebe6aba3b0919) we merged everything now and are currently finishing regression tests on master so we can release by latest tomorrow.

**Comment by stellatores** [comment]
@ReneLindhorst  @danielr we released the new release candidate now: https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.10-rc2. Please let me know if you have any other issues.
