### ISSUE TITLE
Unable to build with Xcode 16 betas

### ISSUE THREAD

**Issue by luis-ifolor** [mapp-digital/MappIntelligence-iOS-v5#14]
Hello
Currently it's not possible to build the Swift Package with Xcode 16 betas (see attached screenshot). 
I see that something similar happened with Xcode 15 betas (https://github.com/mapp-digital/MappIntelligence-iOS-v5/issues/6), I'm wondering if it's an Xcode 16 beta bug or something that needs to be updated in the Swift Package specs?

<img width="614" alt="Mapp issue Xcode 16b" src="https://github.com/user-attachments/assets/4183cdd8-b400-474e-92eb-ec91625ed5db">

**Comment by ortekka** [comment]
This is still happening with the Release Candidate of Xcode 16 (16A242). With the release of iOS 18 only a week away now, this has become an urgent issue.
<img width="601" alt="Screenshot 2024-09-10 at 15 44 50" src="https://github.com/user-attachments/assets/d582736b-c218-4bd3-aff4-74f06400f8d0">

**Comment by luis-ifolor** [comment]
@StefanMiticon Is there any update regarding this issue?

**Comment by stellatores** [comment]
@luis-ifolor we are aware of the issue and are currently working on fixing it. Unfortunately Xcode 16 changed the linking system and we needed to adjust our symlinks one by one. Our developer fixed it just now but it still needs to pass QA. It is currently on branch https://github.com/mapp-digital/MappIntelligence-iOS-v5/tree/SDK-602-xcode-16-spm-compatibility-with-mapp-intelligence - as soon as we are done with testing we can release it officially.

**Comment by ortekka** [comment]
@stellatores: any ETA for when this fix will be merged into the main branch? I'm holding off on updating my Xcode to version 16 just for this issue. Thanks!

**Comment by stellatores** [comment]
@ortekka we needed to change quite a bit but are working on this on high prio. We found the main cause now and are currently working on the fix. If all goes well we will release the updated version by end of this week latest.

**Comment by stellatores** [comment]
@ortekka @luis-ifolor we fixed the issue on our SDK side for SPM and released to SPM and GitHub (https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.12). Unfortunately there is an open issue on CocoaPods that prevents us to publish the version on CocoaPods (https://github.com/CocoaPods/CocoaPods/issues/12583). So currently we run on the following versions for iOS:

* SPM: version 5.0.12
* CocoaPods: version 5.0.11

**Comment by Cordobo** [comment]
We experienced the issue with Xcode 16 and 16.1, replacing (in ios/Podfile)

`pod 'MappIntelligence'`

with 

`pod 'MappIntelligence', :git => 'https://github.com/mapp-digital/MappIntelligence-iOS-v5.git', :tag => '5.0.12' # currently no podspec available for 5.0.12`

worked for us.

HTH

**Comment by stellatores** [comment]
Hi all, we just released version 5.0.12 to CocoaPods now as well. There should not be any problem any more with Xcode 16
