### ISSUE TITLE
5.04.2 broken and 5.0.4.3 podspec leads to CocoaPods and Xcode build warnings

### ISSUE THREAD

**Issue by dockay** [mapp-digital/MappIntelligence-iOS-v5#3]
Your latest version 5.0.4.3 leads to this cocoapods warnings on install:

> [!] [Xcodeproj] Generated duplicate UUIDs:
PBXBuildFile -- Pods.xcodeproj/targets/buildConfigurationList:buildConfigurations:buildSettings:|,displayName:|,isa:|,name:|,,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,defaultConfigurationIsVisible:0,defaultConfigurationName:Release,displayName:ConfigurationList,isa:XCConfigurationList,,buildPhases:buildActionMask:2147483647,displayName:Headers,files:|,isa:PBXHeadersBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:Sources,files:|,|,|,isa:PBXSourcesBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:Frameworks,files:|,isa:PBXFrameworksBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:Resources,files:,isa:PBXResourcesBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildRules:,dependencies:displayName:Base,isa:PBXTargetDependency,targetProxy:containerPortal:|,displayName:|,isa:|,proxyType:|,remoteGlobalIDString:|,remoteInfo:|,,,displayName:DAKTrackingService,isa:PBXTargetDependency,targetProxy:containerPortal:|,displayName:|,isa:|,proxyType:|,remoteGlobalIDString:|,remoteInfo:|,,,displayName:AppVersionService,isa:PBXNativeTarget,name:AppVersionService,packageProductDependencies:,productName:AppVersionService,productReference:displayName:AppVersionService,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:AppVersionService,path:AppVersionService.framework,sourceTree:BUILT_PRODUCTS_DIR,,productType:com.apple.product-type.framework,/dependencies/displayName:DAKTrackingService,isa:PBXTargetDependency,targetProxy:containerPortal:46EB2E00000000,displayName:ContainerItemProxy,isa:PBXContainerItemProxy,proxyType:1,remoteGlobalIDString:46EB2E00014B10,remoteInfo:DAKTrackingService,,/target/dependencies/displayName:MappIntelligence,isa:PBXTargetDependency,targetProxy:containerPortal:46EB2E00000000,displayName:ContainerItemProxy,isa:PBXContainerItemProxy,proxyType:1,remoteGlobalIDString:46EB2E000197B0,remoteInfo:MappIntelligence,,/target/buildPhases/buildActionMask:2147483647,displayName:Headers,files:displayName:MIActionEvent.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIFormSubmitEvent.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIMediaEvent.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIPageViewEvent.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIDeepLink.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIMediaTracker.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXIdentifier.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXInappLogger.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXNetworkManager.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXNetworkMetadata.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXRequest.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXRequestBuilder.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:KeychainManager.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligence.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligenceSDK.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MICampaignParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIDefaultTracker.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIEcommerceParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIEventParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIFormField.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIFormParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIMediaParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIPageParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIParams.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIParamType.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIProduct.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIProperties.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MISessionParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MITrackerRequest.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MITrackingEvent.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIUserCategories.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligenceLogger.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligence.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligenceSDK.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIConfig.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligenceBasicRequestBuilder.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIParams.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIParamType.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIProperties.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIRequestBatchSupportUrlBuilder.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIRequestTrackerBuilder.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIRequestUrlBuilder.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MITrackerRequest.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MITrackingEvent.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIURLSizeMonitor.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIDatabaseManager.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIParameter.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIRequest.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIRequestData.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligenceDefaultConfig.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MICampaignParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIEcommerceParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIEventParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIFormField.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIFormParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIMediaParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIPageParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIProduct.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MISessionParameters.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIUserCategories.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIConfiguration.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIDefaultTracker.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIExceptionTracker.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIUIFlowObserver.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXInappLogger.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXNetworkManager.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXNetworkMetadata.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXRequest.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXRequestBuilder.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:APXIdentifier.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:KeychainManager.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIEnvironment.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligenceiOS.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MIWebViewTracker.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,name:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,displayName:MappIntelligence-umbrella.h,fileRef:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,isa:PBXBuildFile,settings:ATTRIBUTES:|,,,isa:PBXHeadersBuildPhase,runOnlyForDeploymentPostprocessing:0,/files/displayName:MIUserCategories.h,fileRef:displayName:MIUserCategories.h,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:sourcecode.c.h,name:MIUserCategories.h,path:MappIntelligence/Properties/MIUserCategories.h,sourceTree:<group>,,isa:PBXBuildFile,settings:ATTRIBUTES:Public,,

And this build warnings:

Just one as example, there are 25 of them

> Skipping duplicate build file in Copy Headers build phase: /Pods/MappIntelligence/MappIntelligence/UserMatching/DeviceID/APXIdentifier.h

This came in with this commit: [MappIntelligence.podspec](https://github.com/mapp-digital/MappIntelligence-iOS-v5/commit/6d741f9fcf696df11d173587d6704a3d005f5142)

> s.exclude_files = 'MappIntelligence/include/**',

this has been removed and I think this was a mistake.

**Comment by dockay** [comment]
As I digged further into it, it seems its already broken on Version 5.0.4.2. This version doesn't even build at all:

>Build Error: 25 duplicate symbols for architecture arm64

**Comment by Annika-EMP** [comment]
We have the same error in our Project.

**Comment by stellatores** [comment]
This warning comes from a latest Xcode version when using CocoaPods. Please add the following line to the start of your Podfile to remove it:
install! 'cocoapods', :deterministic_uuids => false

Please also check the documentation here  https://guides.cocoapods.org/syntax/podfile.html#install_bang

**Comment by dockay** [comment]
That only suppresses the warning and not the cause of the problem.

**Comment by knox** [comment]
> Please add the following line to the start of your Podfile to remove it:
install! 'cocoapods', :deterministic_uuids => false

This is no acceptable solution as it has a rather massive impact on the overall project setup of the consumer.

Instead, you have to fix your podspec. Please also check the documentation here https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns

**Comment by StefanMiticon** [comment]
Hi all, 

we have publish new version 5.0.4.6 which resolve this issue, give it a try :)

**Comment by dockay** [comment]
Hi @StefanMiticon, thanks for coming back. Its working now!
