### ISSUE TITLE
Memoryleaks in version 5.0.3.1 and 5.0.4.3

### ISSUE THREAD

**Issue by Annika-EMP** [mapp-digital/MappIntelligence-iOS-v5#4]
We have a bunch of MemoryLeaks which appear in our Project for a "libsqlite3.dylib". I can see them in the Profiler and they come from MIDatabaseManager "__35-[MIDatabaseManager deleteRequest:]_block_invoke".

<img width="1618" alt="Screenshot 2023-02-17 at 10 37 23" src="https://user-images.githubusercontent.com/94851541/219611057-6d71ce8a-fecc-4181-bac8-ed4c2f8102da.png">

We use the MappIntelligence Framework in Version 5.0.3.1, but we cannot update due to https://github.com/mapp-digital/MappIntelligence-iOS-v5/issues/3.

**Comment by Annika-EMP** [comment]
I could reproduce the issue as well in Version 5.0.4.3!

**Comment by StefanMiticon** [comment]
Hi @Annika-EMP ,
we just release hot fix for this problem, please try latest version ( 5.0.4.4)

Best Regards,
Stefan Stevanovic

**Comment by stellatores** [comment]
Hi all, 
I am closing this issue as it should be fixed from version 5.0.4.4. If the issue still persists please re-open.
