### ISSUE TITLE
Framework crash in Version 5.0.4.3

### ISSUE THREAD

**Issue by Annika-EMP** [mapp-digital/MappIntelligence-iOS-v5#5]
In the MappIntelligence Framework Version 5.0.4.3, we have a crash at the startup of the app. The problem is, that after initialising we directly do a page tracking.

The exception is the following:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]' 

It crashes due to line 41 as the everID is nil, which we have configured during the init of Webtrekk, directly before the page track. It seems to be a multithreading issue, if I do the tracking later after initialisation it does not crash.
![Screenshot 2023-02-23 at 11 55 32](https://user-images.githubusercontent.com/94851541/220887232-5e238e63-0223-4aea-80c4-2447c35bf963.png)

Code example: the App crashes if the configure directly executed after the init. 
![Screenshot 2023-02-23 at 12 28 15](https://user-images.githubusercontent.com/94851541/220893909-1984153c-0d1a-442e-8679-676b0592e72b.png)

**Comment by stellatores** [comment]
@Annika-EMP that is correct, the initialisation needs to be finished before the first page track request can be sent. Is there a reason you need the call inside the init/configuration method? You can either create the page request outside of the init/configuration method without and data loss, this is how the SDK is supposed to be configured. Or you can delay the execution of the trackPage method by adding the following line of code, this is not what we recommend though:

`DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) { // Change 2.0 to the desired number of seconds.
   // Code you want to be delayed
}`

**Comment by stetbern** [comment]
We encounter the same issue when deactivating anonymous tracking some time after init during regular runtime and directly afterwards e.g. trying to either track something or to get the current everId. Then everything crashes with the same exception as mentioned initally.

**Comment by stellatores** [comment]
Thanks we were able to reproduce the issue and are working on a fix.

**Comment by StefanMiticon** [comment]
Hi all, 

we have publish new version 5.0.4.6 ( https://cocoapods.org/pods/MappIntelligence ) Please try it and see if crash still appears. We have already tested on our end but we would also like your input. 

Best Regards,
Stefan

**Comment by stellatores** [comment]
Hi all,
I am closing this issue as we have released the new version now. If the issue still persist please re-open.
