### ISSUE TITLE
Xcode 15.0 doesn't compile

### ISSUE THREAD

**Issue by matax87** [mapp-digital/MappIntelligence-iOS-v5#6]
In Xcode 15.0 beta 5 (15A5209g) I get the following error

> /Users/matax/Library/Developer/Xcode/DerivedData/InBankMobile-eohyrtzbxxgpqcdnjlyzgjgfpikf/SourcePackages/checkouts/MappIntelligence-iOS-v5/MappIntelligence/Network/Tracking Request/MIURLSizeMonitor.m:10:9: fatal error: 'MappIntelligenceLogger.h' file not found
> #import "MappIntelligenceLogger.h"
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> 
> /Users/matax/Library/Developer/Xcode/DerivedData/InBankMobile-eohyrtzbxxgpqcdnjlyzgjgfpikf/SourcePackages/checkouts/MappIntelligence-iOS-v5/MappIntelligence/Network/Tracking Request/MIURLSizeMonitor.m:10:9: 'MappIntelligenceLogger.h' file not found
 
I'm using v5.0.4 via Swift PM

**Comment by stellatores** [comment]
Thanks Matax, our SDK works with the current stable version of Xcode and we will ensure it works with Xcode 15 once it is out of beta.

**Comment by matax87** [comment]
@stellatores any update on this? Xcode 15GM is out.

Thank you

**Comment by stellatores** [comment]
@matax87  we didn't experience any issues with the stable version of Xcode and our SDK. Please let us know if it does not work for you.

**Comment by stellatores** [comment]
Closing this issue for now, if there are any remaining issues with Xcode 15 please let us know
