### ISSUE TITLE
GENERATE_INFOPLIST_FILE in user_target_xconfing breaks build in 5.0.5

### ISSUE THREAD

**Issue by stetbern** [mapp-digital/MappIntelligence-iOS-v5#7]
With the newest version 5.0.5 we get an error on build e.g. on the simulator:

```
The application's Info.plist does not contain a valid CFBundleShortVersionString.
Ensure your bundle contains a valid CFBundleShortVersionString.
```

In our app's Info.plist a valid CFBundleShortVersionString is defined. This error also only occurs when using the version 5.0.5 of MappIntelligence.

As far as I can see this is due to GENERATE_INFOPLIST_FILE in user_target_xconfing in the podspec file. As said in the podspec reference, the attribute itself is not recommended: https://guides.cocoapods.org/syntax/podspec.html#user_target_xcconfig.

**Comment by stellatores** [comment]
@stetbern  we published a hotfix for this issue (https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.5.1) Please let us know if you still encounter the issue with the new version.
