### ISSUE TITLE
SPM Package for 5.0.6.3 broken, ReadMe.md wrong

### ISSUE THREAD

**Issue by winkelsdorf** [mapp-digital/MappIntelligence-iOS-v5#8]
The current SPM Package for `5.0.6.3` references an invalid Path regarding watchOS:

<img width="831" alt="image" src="https://github.com/mapp-digital/MappIntelligence-iOS-v5/assets/1413291/c8390fb4-3bbc-4782-8fe2-ecd6984b586d">

The ReadMe is also wrong about the Versioning:
`5.0.6.3` is not a valid Package Version:

<img width="469" alt="image" src="https://github.com/mapp-digital/MappIntelligence-iOS-v5/assets/1413291/35fe64df-526b-460d-9ddc-cd0c7d6757e0">

In the ReadMe:
> dependencies: [ .package(url: "https://github.com/mapp-digital/MappIntelligence-iOS-v5.git", .upToNextMajor(from: "5.0.6.3")) ]

Afaik only SemVer Major.Minor.Patch are supported, you should better raise the patch level instead of adding build versions.

**Comment by manuelescrig** [comment]
Same issue here. Would be great if the SDK could support SemVer Major.Minor.Patch. 

SPM doesn't supports versioning like 5.0.6.4.

**Comment by stellatores** [comment]
Hi both, thank you for your input. We changed the versioning to https://github.com/mapp-digital/MappIntelligence-iOS-v5/releases/tag/5.0.6-rc1 for now which works with SPM and also includes the fixes for the wrong path. Please try this one to see if it fixes your issues.

**Comment by winkelsdorf** [comment]
@stellatores For me this is still resolving to the wrong `5.0.6`

<img width="829" alt="image" src="https://github.com/mapp-digital/MappIntelligence-iOS-v5/assets/1413291/9b8b518d-17d9-4ae9-8b2d-0f17a55c69c6">

Our `Package.swift` includes it like this:
```swift
dependencies: [
        .package(
            url: "https://github.com/mapp-digital/MappIntelligence-iOS-v5",
            .upToNextMajor(from: "5.0.6")
        ),
```

I guess SPM does not resolve to `-rc` Versions automatically. Which leads back to the suggestion, it's probably best to publish a `5.0.7`.

**Comment by stellatores** [comment]
@winkelsdorf your Package.swift file only accepts the next major version, this is why it does not work with the new version. Please change it to the exact version and use the -rc one. Changing the major version every time we change / fix just one feature is not possible for us unfortunately. Please let me know if you still run into issues when using the exact version (as described here: https://developer.apple.com/documentation/packagedescription/package/dependency/requirement-swift.enum/exact(_:))

**Comment by winkelsdorf** [comment]
@stellatores Thank you for your answer!

> @winkelsdorf your Package.swift file only accepts the next major version, this is why it does not work with the new version. Please change it to the exact version and use the -rc one. Changing the major version every time we change / fix just one feature is not possible for us unfortunately. 

`.uptoNextMajor(from:)` is a range: starting from 5.0.0 to 5.x.x, but excluding `6.x.x`. So that range is technically correct, isn't it? But SPM ignores `-rc` and defaults to `5.0.6` when a range is used, obviously to exclude pre-releases, flavors and release candidates.

I was speaking about raising the patch, not major or minor. That would work out of the box and supports updating the packages without editing the specification.

But yes: of course specifying the exact works, thanks for the recommendation and the fix. As we want to stick to automated CI/CD Updates, we will revert to use a range as soon as `5.0.7` is out.

Feel free to close, as the most important part was to drop the 4th version number. This works now, thank you!

**Comment by ortekka** [comment]
I second @manuelescrig's suggestion: the SDK should really follow semantic versioning rules like just about all Swift packages currently circulating. Straying from semantic versioning will cost headaches and wasted time for developers, and possibly your tech support as well.

**Comment by stellatores** [comment]
Thanks all for your feedback. In the future, we continue to release our regular, scheduled updates with the following versioning:
major.minor.patch

For hotfixes and quick fixes outside of our regular releases we will use the following syntax:
major.minor.patch-rc1-n
